version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - checkout # check out the code in the project directory
      - run: yarn
      - run: yarn lint
      - run: yarn test-expressions
      - run: yarn test-unit
