version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
        auth:
          username: nicolasjutheodo
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world"
